export default {
  categories: {
    bestPicture: {
      value: 16,
      name: "Best Picture",
      nominees: [
        { text: "The Father" },
        { text: "Judas and the Black Messiah" },
        { text: "Mank" },
        { text: "Minari" },
        { text: "Nomadland" },
        { text: "Promising Young Woman" },
        { text: "Sound of Metal" },
        { text: "The Trial of the Chicago 7" },
      ],
      order: 0,
    },
    bestActor: {
      value: 8,
      name: "Actor in a Leading Role",
      nominees: [
        { text: "Riz Ahmed", secondaryText: "Sound of Metal" },
        {
          text: "Chadwick Boseman",
          secondaryText: "Ma Rainey's Black Bottom",
        },
        { text: "Anthony Hopkins", secondaryText: "The Father" },
        { text: "Gary Oldman", secondaryText: "Mank" },
        { text: "Steven Yeun", secondaryText: "Minari" },
      ],
      order: 1,
    },
    bestActress: {
      value: 8,
      name: "Actress in a Leading Role",
      nominees: [
        { text: "Viola Davis", secondaryText: "Ma Rainey's Black Bottom" },
        {
          text: "Andra Day",
          secondaryText: "The United States v. Billie Holiday",
        },
        { text: "Vanessa Kirby", secondaryText: "Pieces of a Woman" },
        { text: "Frances McDormand", secondaryText: "Nomadland" },
        { text: "Carey Mulligan", secondaryText: "Promising Young Woman" },
      ],
      order: 2,
    },
    bestSupportingActor: {
      value: 4,
      name: "Actor in a Supporting Role",
      nominees: [
        {
          text: "Sacha Baron Cohen",
          secondaryText: "The Trial of the Chicago ",
        },
        {
          text: "Daniel Kaluuya",
          secondaryText: "Judas and the Black Messiah",
        },
        {
          text: "Leslie Odom Jr.",
          secondaryText: "One Night in Miami",
        },
        { text: "Paul Raci", secondaryText: "Sound of Metal" },
        {
          text: "Lakeith Stanfield",
          secondaryText: "Judas and the Black Messiah",
        },
      ],
      order: 3,
    },
    bestSupportingActress: {
      value: 4,
      name: "Actress in a Supporting Role",
      nominees: [
        { text: "Maria Bakalova", secondaryText: "Borat Subsequent Moviefilm" },
        { text: "Glenn Close", secondaryText: "Hillbilly Elegy" },
        { text: "Olivia Colman", secondaryText: "The Father" },
        { text: "Amanda Seyfried", secondaryText: "Mank" },
        { text: "Youn Yuh-jung", secondaryText: "Minari" },
      ],
      order: 4,
    },
    directing: {
      value: 4,
      name: "Directing",
      nominees: [
        { text: "Another Round", secondaryText: "Thomas Vinterberg" },
        { text: "Mank", secondaryText: "David Fincher" },
        { text: "Minari", secondaryText: "Lee Isaac Chung" },
        {
          text: "Nomadland",
          secondaryText: "Chloé Zhao",
        },
        { text: "Promising Young Woman", secondaryText: "Emerald Fennell" },
      ],
      order: 5,
    },
    documentaryFeature: {
      value: 4,
      name: "Documentary Feature",
      nominees: [
        { text: "Collective" },
        {
          text: "Crip Camp",
          movieDBName: "Crip Camp: A Disability Revolution",
        },
        { text: "The Mole Agent" },
        { text: "My Octopus Teacher" },
        { text: "Time" },
      ],
      order: 6,
    },
    foreignLanguageFile: {
      value: 4,
      name: "International Feature Film",
      nominees: [
        { text: "Another Round", secondaryText: "Denmark" },
        { text: "Better Days", secondaryText: "Hong Kong" },
        { text: "Collective", secondaryText: "Romania" },
        { text: "The Man Who Sold His Skin", secondaryText: "Tunisia" },
        { text: "Quo Vadis, Aida?", secondaryText: "Bosnia and Herzegovina" },
      ],
      order: 7,
    },
    animatedFeature: {
      value: 4,
      name: "Animated Feature Film",
      nominees: [
        { text: "Onward" },
        { text: "Over the Moon" },
        { text: "A Shaun the Sheep Movie: Farmageddon" },
        { text: "Soul" },
        { text: "Wolfwalkers" },
      ],
      order: 8,
    },
    writingAdaptedScreenplay: {
      value: 2,
      name: "Writing (Adapted Screenplay)",
      nominees: [
        { text: "Borat Subsequent Moviefilm" },
        { text: "The Father" },
        { text: "Nomadland" },
        { text: "One Night in Miami", movieDBName: "One Night in Miami..." },
        { text: "The White Tiger" },
      ],
      order: 9,
    },
    writingOriginalScreenplay: {
      value: 2,
      name: "Writing (Original Screenplay)",
      nominees: [
        { text: "Judas and the Black Messiah" },
        { text: "Minari" },
        { text: "Promising Young Woman" },
        { text: "Sound of Metal" },
        { text: "The Trial of the Chicago 7" },
      ],
      order: 10,
    },
    cinematography: {
      value: 2,
      name: "Cinematography",
      nominees: [
        { text: "Judas and the Black Messiah" },
        { text: "Mank" },
        { text: "News of the World" },
        { text: "Nomadland" },
        { text: "The Trial of the Chicago 7" },
      ],
      order: 11,
    },
    documentaryShort: {
      value: 2,
      name: "Documentary Short Subject",
      nominees: [
        { text: "Colette" },
        { text: "A Concerto Is a Conversation" },
        { text: "Do Not Split" },
        { text: "Hunger Ward" },
        { text: "A Love Song for Latasha" },
      ],
      order: 12,
    },
    filmEditing: {
      value: 1,
      name: "Film Editing",
      nominees: [
        { text: "The Father" },
        { text: "Nomadland" },
        { text: "Promising Young Woman" },
        { text: "Sound of Metal" },
        { text: "The Trial of the Chicago 7" },
      ],
      order: 13,
    },
    musicOriginalScore: {
      value: 1,
      name: "Music (Original Score)",
      nominees: [
        { text: "Da 5 Bloods", secondaryText: "Terence Blanchard" },
        { text: "Mank", secondaryText: "Trent Reznor, Atticus Ross" },
        { text: "Minari", secondaryText: "Emile Mosseri" },
        { text: "News of the World", secondaryText: "James Newton Howard" },
        {
          text: "Soul",
          secondaryText: "Trent Reznor, Atticus Ross, Jon Batiste",
        },
      ],
      order: 14,
    },
    musicOriginalSong: {
      value: 1,
      name: "Music (Original Song)",
      nominees: [
        {
          text: "Judas and the Black Messiah",
          secondaryText: "Fight for You",
        },
        { text: "The Trial of the Chicago 7", secondaryText: "Hear My Voice" },
        {
          text: "Húsavík",
          secondaryText: "Eurovision Song Contest",
          movieDBName: "Eurovision Song Contest: The Story of Fire Saga",
        },
        { text: "The Life Ahead", secondaryText: "Io Si (Seen)" },
        {
          text: "One Night in Miami",
          secondaryText: "Speak Now",
          movieDBName: "One Night in Miami...",
        },
      ],
      order: 15,
    },
    shortFilmAnimated: {
      value: 1,
      name: "Short Film (Animated)",
      nominees: [
        { text: "Burrow" },
        { text: "Genius Loci" },
        { text: "If Anything Happens I Love You" },
        { text: "Opera" },
        { text: "Yes-People" },
      ],
      order: 16,
    },
    shortFilmLiveAction: {
      value: 1,
      name: "Short Film (Live Action)",
      nominees: [
        { text: "Feeling Through" },
        { text: "The Letter Room" },
        { text: "The Present" },
        { text: "Two Distant Strangers" },
        { text: "White Eye" },
      ],
      order: 17,
    },
    sound: {
      value: 1,
      name: "Sound",
      nominees: [
        { text: "Greyhound" },
        { text: "Mank" },
        { text: "News of the World" },
        { text: "Soul" },
        { text: "Sound of Metal" },
      ],
      order: 18,
    },
    visualEffects: {
      value: 1,
      name: "Visual Effects",
      nominees: [
        { text: "Love and Monsters" },
        { text: "The Midnight Sky" },
        { text: "Mulan" },
        { text: "The One and Only Ivan" },
        { text: "Tenet" },
      ],
      order: 19,
    },
    productionDesign: {
      value: 1,
      name: "Production Design",
      nominees: [
        { text: "The Father" },
        { text: "Ma Rainey's Black Bottom" },
        { text: "Mank" },
        { text: "News of the World" },
        { text: "Tenet" },
      ],
      order: 20,
    },
    costumeDesign: {
      value: 1,
      name: "Costume Design",
      nominees: [
        { text: "Emma." },
        { text: "Mank" },
        { text: "Ma Rainey's Black Bottom" },
        { text: "Mulan" },
        { text: "Pinocchio" },
      ],
      order: 21,
    },
    makeupAndHairstyling: {
      value: 1,
      name: "Makeup and Hairstyling",
      nominees: [
        { text: "Emma." },
        { text: "Hillbilly Elegy" },
        { text: "Ma Rainey's Black Bottom" },
        { text: "Mank" },
        { text: "Pinocchio" },
      ],
      order: 22,
    },
  },
};
