export default {
  categories: {
    bestMotionPictureDrama: {
      value: 16,
      name: "Best Picture Drama",
      nominees: [
        { text: "Belfast" },
        { text: "CODA" },
        { text: "Dune" },
        { text: "King Richard" },
        { text: "The Power of the Dog" },
      ],
      order: 0,
    },
    bestMotionPictureMusicalComedy: {
      value: 16,
      name: "Best Picture – Musical/Comedy",
      nominees: [
        { text: "Cyrano" },
        { text: "Don't Look Up" },
        { text: "Licorice Pizza" },
        { text: "tick, tick… BOOM!" },
        { text: "West Side Story" },
      ],
      order: 1,
    },
    bestTvSeriesDrama: {
      value: 16,
      name: "Best Drama Series",
      nominees: [
        { text: "Lupin" },
        { text: "The Morning Show" },
        { text: "Pose" },
        { text: "Squid Game" },
        { text: "Succession" },
      ],
      order: 2,
    },
    bestTvSeriesMusicalComedy: {
      value: 16,
      name: "Best Musical/Comedy Series",
      nominees: [
        { text: "The Great" },
        { text: "Hacks" },
        { text: "Only Murders in the Building" },
        { text: "Reservation Dogs" },
        { text: "Ted Lasso" },
      ],
      order: 3,
    },
    limitedSeriesTV: {
      value: 16,
      name: "Best Television Motion Picture",
      nominees: [
        { text: "Dopesick" },
        {
          text: "Impeachment: American Crime Story",
          movieDBName: "American Crime Story",
        },
        { text: "Maid" },
        { text: "Mare of Easttown" },
        { text: "The Underground Railroad" },
      ],
      order: 4,
    },
    bestActressDrama: {
      value: 8,
      name: "Best Actress - Motion Picture Drama",
      nominees: [
        { text: "Jessica Chastain", secondaryText: "Eyes of Tammy Faye, The" },
        { text: "Olivia Colman", secondaryText: "The Lost Daughter" },
        { text: "Nicole Kidman", secondaryText: "Being the Ricardos" },
        { text: "Lady Gaga", secondaryText: "House of Gucci" },
        { text: "Kristen Stewart", secondaryText: "Spencer" },
      ],
      order: 5,
    },
    bestActorDrama: {
      value: 8,
      name: "Best Actor - Motion Picture Drama",
      nominees: [
        { text: "Mahershala Ali", secondaryText: "Swan Song" },
        { text: "Javier Bardem", secondaryText: "Being the Ricardos" },
        {
          text: "Benedict Cumberbatch",
          secondaryText: "The Power of the Dog",
        },
        { text: "Will Smith", secondaryText: "King Richard" },
        { text: "Denzel Washington", secondaryText: "Tragedy of Macbeth, The" },
      ],
      order: 6,
    },
    bestActressMusicalComedy: {
      value: 8,
      name: "Best Actress - Motion Picture – Musical/Comedy",
      nominees: [
        { text: "Marion Cotillard", secondaryText: "Annette" },
        { text: "Alana Haim", secondaryText: "Licorice Pizza" },
        { text: "Jennifer Lawrence", secondaryText: "Don't Look Up" },
        { text: "Emma Stone", secondaryText: "Cruella" },
        { text: "Rachel Zegler", secondaryText: "West Side Story" },
      ],
      order: 7,
    },
    bestActorMusicalComedy: {
      value: 8,
      name: "Best Actor - Motion Picture – Musical/Comedy",
      nominees: [
        { text: "Leonardo DiCaprio", secondaryText: "Don't Look Up" },
        { text: "Peter Dinklage", secondaryText: "Cyrano" },
        { text: "Andrew Garfield", secondaryText: "tick, tick… BOOM!" },
        { text: "Cooper Hoffman", secondaryText: "Licorice Pizza" },
        { text: "Anthony Ramos", secondaryText: "In the Heights" },
      ],
      order: 8,
    },
    bestActressTVDrama: {
      value: 8,
      name: "Best Television Actress – Drama Series",
      nominees: [
        { text: "Uzo Aduba", secondaryText: "In Treatment" },
        { text: "Jennifer Aniston", secondaryText: "The Morning Show" },
        { text: "Christine Baranski", secondaryText: "Good Fight, The" },
        { text: "Elisabeth Moss", secondaryText: "Handmaid's Tale, The" },
        {
          text: "Michaela Jaé Rodriguez",
          secondaryText: "Pose",
          movieDBName: "MJ Rodriguez",
        },
      ],
      order: 9,
    },
    bestActorTVDrama: {
      value: 8,
      name: "Best Television Actor – Drama Series",
      nominees: [
        { text: "Brian Cox", secondaryText: "Succession" },
        { text: "Lee Jung-jae", secondaryText: "Squid Game" },
        { text: "Billy Porter", secondaryText: "Pose" },
        { text: "Jeremy Strong", secondaryText: "Succession" },
        { text: "Omar Sy", secondaryText: "Lupin" },
      ],
      order: 10,
    },
    bestActressTVMusicalComedy: {
      value: 8,
      name: "Best Television Actress – Musical/Comedy Series",
      nominees: [
        { text: "Hannah Einbinder", secondaryText: "Hacks" },
        { text: "Elle Fanning", secondaryText: "The Great" },
        { text: "Issa Rae", secondaryText: "Insecure" },
        { text: "Tracee Ellis Ross", secondaryText: "Black-ish" },
        { text: "Jean Smart", secondaryText: "Hacks" },
      ],
      order: 11,
    },
    bestActorTVMusicalComedy: {
      value: 8,
      name: "Best Television Actor – Musical/Comedy Series",
      nominees: [
        { text: "Anthony Anderson", secondaryText: "Black-ish" },
        { text: "Nicholas Hoult", secondaryText: "The Great" },
        { text: "Steve Martin", secondaryText: "Only Murders in the Building" },
        { text: "Martin Short", secondaryText: "Only Murders in the Building" },
        { text: "Jason Sudeikis", secondaryText: "Ted Lasso" },
      ],
      order: 12,
    },
    bestActorLimitedTV: {
      value: 8,
      name: "Best Actor - Television Motion Picture",
      nominees: [
        { text: "Paul Bettany", secondaryText: "WandaVision" },
        { text: "Oscar Isaac", secondaryText: "Scenes from a Marriage-TV" },
        { text: "Michael Keaton", secondaryText: "Dopesick" },
        { text: "Ewan McGregor", secondaryText: "Halston" },
        { text: "Tahar Rahim", secondaryText: "Serpent, The" },
      ],
      order: 13,
    },
    bestActressLimitedTV: {
      value: 8,
      name: "Best Actress - Television Motion Picture",
      nominees: [
        {
          text: "Jessica Chastain",
          secondaryText: "Scenes from a Marriage-TV",
        },
        { text: "Cynthia Erivo", secondaryText: "Genius: Aretha" },
        { text: "Elizabeth Olsen", secondaryText: "WandaVision" },
        { text: "Margaret Qualley", secondaryText: "Maid" },
        { text: "Kate Winslet", secondaryText: "Mare of Easttown" },
      ],
      order: 14,
    },
    bestSupportingActor: {
      value: 4,
      name: "Best Supporting Actor - Motion Picture",
      nominees: [
        { text: "Ben Affleck", secondaryText: "Tender Bar, The" },
        { text: "Jamie Dornan", secondaryText: "Belfast" },
        { text: "Ciarán Hinds", secondaryText: "Belfast" },
        { text: "Troy Kotsur", secondaryText: "CODA" },
        { text: "Kodi Smit-McPhee", secondaryText: "The Power of the Dog" },
      ],
      order: 15,
    },
    bestSupportingActress: {
      value: 4,
      name: "Best Supporting Actress - Motion Picture",
      nominees: [
        { text: "Caitriona Balfe", secondaryText: "Belfast" },
        { text: "Ariana DeBose", secondaryText: "West Side Story" },
        { text: "Kirsten Dunst", secondaryText: "The Power of the Dog" },
        { text: "Aunjanue Ellis", secondaryText: "King Richard" },
        { text: "Ruth Negga", secondaryText: "Passing" },
      ],
      order: 16,
    },
    bestSupportingActorTV: {
      value: 4,
      name: "Best Supporting Actor - Television",
      nominees: [
        { text: "Billy Crudup", secondaryText: "The Morning Show" },
        { text: "Kieran Culkin", secondaryText: "Succession" },
        { text: "Mark Duplass", secondaryText: "The Morning Show" },
        { text: "Brett Goldstein", secondaryText: "Ted Lasso" },
        { text: "Oh Yeong-su", secondaryText: "Squid Game" },
      ],
      order: 17,
    },
    bestSupportingActressTV: {
      value: 4,
      name: "Best Supporting Actress – Television",
      nominees: [
        { text: "Jennifer Coolidge", secondaryText: "White Lotus, The" },
        { text: "Kaitlyn Dever", secondaryText: "Dopesick" },
        { text: "Andie MacDowell", secondaryText: "Maid" },
        { text: "Sarah Snook", secondaryText: "Succession" },
        { text: "Hannah Waddingham", secondaryText: "Ted Lasso" },
      ],
      order: 18,
    },
    animatedFeature: {
      value: 4,
      name: "Best Picture – Animated",
      nominees: [
        { text: "Encanto" },
        { text: "Flee" },
        { text: "Luca" },
        { text: "My Sunny Maad" },
        { text: "Raya and the Last Dragon" },
      ],
      order: 19,
    },
    directing: {
      value: 4,
      name: "Best Director Motion Picture",
      nominees: [
        { secondaryText: "Belfast", text: "Kenneth Branagh" },
        { secondaryText: "The Power of the Dog", text: "Jane Campion" },
        { secondaryText: "The Lost Daughter", text: "Maggie Gyllenhaal" },
        { secondaryText: "West Side Story", text: "Steven Spielberg" },
        { secondaryText: "Dune", text: "Denis Villeneuve" },
      ],
      order: 20,
    },
    foreignLanguageFile: {
      value: 4,
      name: "Best Picture – Non-English Language",
      nominees: [
        { text: "Compartment No. 6", secondaryText: "Germany,Russia,Finland" },
        { text: "Drive My Car", secondaryText: "Japan" },
        { text: "The Hand of God", secondaryText: "Italy" },
        { text: "A Hero", secondaryText: "Iran,France" },
        { text: "Parallel Mothers", secondaryText: "Spain" },
      ],
      order: 21,
    },
    musicOriginalScore: {
      value: 1,
      name: "Best Score Motion Picture",
      nominees: [
        { text: "The French Dispatch", secondaryText: "Alexandre Desplat" },
        { text: "Encanto", secondaryText: "Germaine Franco" },
        { text: "The Power of the Dog", secondaryText: "Jonny Greenwood" },
        { text: "Parallel Mothers", secondaryText: "Alberto Iglesias" },
        { text: "Dune", secondaryText: "Hans Zimmer" },
      ],
      order: 22,
    },
    musicOriginalSong: {
      value: 1,
      name: "Best Original Song in a Motion Picture",
      nominees: [
        { text: "King Richard", secondaryText: "Be Alive" },
        { text: "Encanto", secondaryText: "Dos Oruguitas" },
        { text: "Belfast", secondaryText: "Down to Joy" },
        { text: "Respect", secondaryText: "Here I Am (Singing My Way Home)" },
        { text: "No Time To Die", secondaryText: "No Time To Die" },
      ],
      order: 23,
    },
    screenplay: {
      value: 2,
      name: "Best Screenplay Motion Picture",
      nominees: [
        { secondaryText: "Licorice Pizza", text: "Paul Thomas Anderson" },
        { secondaryText: "Belfast", text: "Kenneth Branagh" },
        { secondaryText: "The Power of the Dog", text: "Jane Campion" },
        { secondaryText: "Don't Look Up", text: "Adam McKay" },
        { secondaryText: "Being the Ricardos", text: "Aaron Sorkin" },
      ],
      order: 24,
    },
  },
};
