export default {
  categories: {
    bestPicture: {
      value: 16,
      name: "Best Picture",
      nominees: [
        { text: "Belfast" },
        { text: "CODA" },
        { text: "Don't Look Up" },
        { text: "Drive My Car" },
        { text: "Dune" },
        { text: "King Richard" },
        { text: "Licorice Pizza" },
        { text: "Nightmare Alley" },
        { text: "The Power of the Dog" },
        { text: "West Side Story" },
      ],
      order: 0,
    },
    bestActor: {
      value: 8,
      name: "Actor in a Leading Role",
      nominees: [
        { text: "Javier Bardem", secondaryText: "Being the Ricardos" },
        {
          text: "Benedict Cumberbatch",
          secondaryText: "The Power of the Dog",
        },
        { text: "Andrew Garfield", secondaryText: "tick, tick… BOOM!" },
        { text: "Will Smith", secondaryText: "King Richard" },
        { text: "Denzel Washington", secondaryText: "The Tragedy of Macbeth" },
      ],
      order: 1,
    },
    bestActress: {
      value: 8,
      name: "Actress in a Leading Role",
      nominees: [
        { text: "Jessica Chastain", secondaryText: "The Eyes of Tammy Faye" },
        { text: "Olivia Colman", secondaryText: "The Lost Daughter" },
        { text: "Penélope Cruz", secondaryText: "Parallel Mothers" },
        { text: "Nicole Kidman", secondaryText: "Being the Ricardos" },
        { text: "Kristen Stewart", secondaryText: "Spencer" },
      ],
      order: 2,
    },
    bestSupportingActor: {
      value: 4,
      name: "Actor in a Supporting Role",
      nominees: [
        { text: "Ciarán Hinds", secondaryText: "Belfast" },
        { text: "Troy Kotsur", secondaryText: "CODA" },
        { text: "Jesse Plemons", secondaryText: "The Power of the Dog" },
        { text: "J.K. Simmons", secondaryText: "Being the Ricardos" },
        { text: "Kodi Smit-McPhee", secondaryText: "The Power of the Dog" },
      ],
      order: 3,
    },
    bestSupportingActress: {
      value: 4,
      name: "Actress in a Supporting Role",
      nominees: [
        { text: "Jessie Buckley", secondaryText: "The Lost Daughter" },
        { text: "Ariana DeBose", secondaryText: "West Side Story" },
        { text: "Judi Dench", secondaryText: "Belfast" },
        { text: "Kirsten Dunst", secondaryText: "The Power of the Dog" },
        { text: "Aunjanue Ellis", secondaryText: "King Richard" },
      ],
      order: 4,
    },
    directing: {
      value: 8,
      name: "Directing",
      nominees: [
        { text: "Belfast", secondaryText: "Kenneth Branagh" },
        { text: "Drive My Car", secondaryText: "Ryusuke Hamaguchi" },
        { text: "Licorice Pizza", secondaryText: "Paul Thomas Anderson" },
        { text: "The Power of the Dog", secondaryText: "Jane Campion" },
        { text: "West Side Story", secondaryText: "Steven Spielberg" },
      ],
      order: 5,
    },
    documentaryFeature: {
      value: 4,
      name: "Documentary Feature",
      nominees: [
        { text: "Ascension", movieDBName: "登楼叹" },
        { text: "Attica" },
        { text: "Flee" },
        {
          text:
            "Summer of Soul (...Or, When the Revolution Could Not Be Televised)",
        },
        { text: "Writing With Fire" },
      ],
      order: 6,
    },
    internationalFilm: {
      value: 4,
      name: "International Feature Film",
      nominees: [
        { text: "Drive My Car", secondaryText: "Japan" },
        { text: "Flee", secondaryText: "Denmark" },
        { text: "The Hand of God", secondaryText: "Italy" },
        { text: "Lunana: A Yak in the Classroom", secondaryText: "Bhutan" },
        { text: "The Worst Person in the World", secondaryText: "Norway" },
      ],
      order: 7,
    },
    animatedFeature: {
      value: 4,
      name: "Animated Feature Film",
      nominees: [
        { text: "Encanto" },
        { text: "Flee" },
        { text: "Luca" },
        { text: "The Mitchells vs. the Machines" },
        { text: "Raya and the Last Dragon" },
      ],
      order: 8,
    },
    writingAdaptedScreenplay: {
      value: 2,
      name: "Writing (Adapted Screenplay)",
      nominees: [
        { text: "CODA" },
        { text: "Drive My Car" },
        { text: "Dune" },
        { text: "The Lost Daughter" },
        { text: "The Power of the Dog" },
      ],
      order: 9,
    },
    writingOriginalScreenplay: {
      value: 2,
      name: "Writing (Original Screenplay)",
      nominees: [
        { text: "Belfast" },
        { text: "Don't Look Up" },
        { text: "King Richard" },
        { text: "Licorice Pizza" },
        { text: "The Worst Person in the World" },
      ],
      order: 10,
    },
    cinematography: {
      value: 2,
      name: "Cinematography",
      nominees: [
        { text: "Dune" },
        { text: "Nightmare Alley" },
        { text: "The Power of the Dog" },
        { text: "The Tragedy of Macbeth" },
        { text: "West Side Story" },
      ],
      order: 11,
    },
    documentaryShort: {
      value: 2,
      name: "Documentary Short Subject",
      nominees: [
        { text: "Audible" },
        { text: "Lead Me Home" },
        { text: "The Queen of Basketball" },
        { text: "Three Songs for Benazir" },
        { text: "When We Were Bullies" },
      ],
      order: 12,
    },
    filmEditing: {
      value: 1,
      name: "Film Editing",
      nominees: [
        { text: "Don't Look Up" },
        { text: "Dune" },
        { text: "King Richard" },
        { text: "The Power of the Dog" },
        { text: "tick, tick… BOOM!" },
      ],
      order: 13,
    },
    musicOriginalScore: {
      value: 1,
      name: "Music (Original Score)",
      nominees: [
        { text: "Don't Look Up", secondaryText: "Nicholas Britell" },
        { text: "Dune", secondaryText: "Hans Zimmer" },
        { text: "Encanto", secondaryText: "Germaine Franco" },
        { text: "Parallel Mothers", secondaryText: "Alberto Iglesias" },
        { text: "The Power of the Dog", secondaryText: "Jonny Greenwood" },
      ],
      order: 14,
    },
    musicOriginalSong: {
      value: 1,
      name: "Music (Original Song)",
      nominees: [
        { text: "King Richard", secondaryText: "Be Alive" },
        { text: "Encanto", secondaryText: "Dos Oruguitas" },
        { text: "Belfast", secondaryText: "Down to Joy" },
        { text: "No Time to Die", secondaryText: "No Time to Die" },
        { text: "Four Good Days", secondaryText: "Somehow You Do" },
      ],
      order: 15,
    },
    shortFilmAnimated: {
      value: 1,
      name: "Short Film (Animated)",
      nominees: [
        { text: "Affairs of the Art" },
        { text: "Bestia" },
        { text: "Boxballet" },
        { text: "Robin Robin" },
        { text: "The Windshield Wiper" },
      ],
      order: 16,
    },
    shortFilmLiveAction: {
      value: 1,
      name: "Short Film (Live Action)",
      nominees: [
        { text: "Ala Kachuu — Take and Run", movieDBName: "Ala Kachuu" },
        { text: "The Dress", movieDBName: "SUKIENKA" },
        { text: "The Long Goodbye" },
        { text: "On My Mind" },
        { text: "Please Hold" },
      ],
      order: 17,
    },
    sound: {
      value: 1,
      name: "Sound",
      nominees: [
        { text: "Belfast" },
        { text: "Dune" },
        { text: "No Time to Die" },
        { text: "The Power of the Dog" },
        { text: "West Side Story" },
      ],
      order: 18,
    },
    visualEffects: {
      value: 1,
      name: "Visual Effects",
      nominees: [
        { text: "Dune" },
        { text: "Free Guy" },
        { text: "No Time to Die" },
        { text: "Shang-Chi and the Legend of the Ten Rings" },
        { text: "Spider-Man: No Way Home" },
      ],
      order: 19,
    },
    productionDesign: {
      value: 1,
      name: "Production Design",
      nominees: [
        { text: "Dune" },
        { text: "Nightmare Alley" },
        { text: "The Power of the Dog" },
        { text: "The Tragedy of Macbeth" },
        { text: "West Side Story" },
      ],
      order: 20,
    },
    costumeDesign: {
      value: 1,
      name: "Costume Design",
      nominees: [
        { text: "Cruella" },
        { text: "Cyrano" },
        { text: "Dune" },
        { text: "Nightmare Alley" },
        { text: "West Side Story" },
      ],
      order: 21,
    },
    makeupAndHairstyling: {
      value: 1,
      name: "Makeup and Hairstyling",
      nominees: [
        { text: "Coming 2 America" },
        { text: "Cruella" },
        { text: "Dune" },
        { text: "The Eyes of Tammy Faye" },
        { text: "House of Gucci" },
      ],
      order: 22,
    },
  },
};
