export default {
  categories: {
    bestPicture: {
      value: 16,
      name: "Best Picture",
      nominees: [
        { text: "All Quiet on the Western Front" },
        { text: "Avatar: The Way of Water" },
        { text: "The Banshees of Inisherin" },
        { text: "Elvis" },
        { text: "Everything Everywhere All at Once" },
        { text: "The Fabelmans" },
        { text: "Tár" },
        { text: "Top Gun: Maverick" },
        { text: "Triangle of Sadness" },
        { text: "Women Talking" },
      ],
      order: 0,
    },
    bestActor: {
      value: 8,
      name: "Actor in a Leading Role",
      nominees: [
        { text: "Austin Butler", secondaryText: "Elvis" },
        {
          text: "Colin Farrell",
          secondaryText: "The Banshees of Inisherin",
        },
        { text: "Brendan Fraser", secondaryText: "The Whale" },
        { text: "Paul Mescal", secondaryText: "Aftersun" },
        { text: "Bill Nighy", secondaryText: "Living" },
      ],
      order: 1,
    },
    bestActress: {
      value: 8,
      name: "Actress in a Leading Role",
      nominees: [
        { text: "Cate Blanchett", secondaryText: "Tár" },
        { text: "Ana de Arma", secondaryText: "Blonde" },
        { text: "Andrea Riseborough", secondaryText: "To Leslie" },
        { text: "Michelle Williams", secondaryText: "The Fabelmans" },
        {
          text: "Michelle Yeoh",
          secondaryText: "Everything Everywhere All at Once",
        },
      ],
      order: 2,
    },
    bestSupportingActor: {
      value: 4,
      name: "Actor in a Supporting Role",
      nominees: [
        { text: "Brendan Gleeson", secondaryText: "The Banshees of Inisherin" },
        { text: "Brian Tyree Henry", secondaryText: "Causeway" },
        { text: "Judd Hirsch", secondaryText: "The Fabelmans" },
        { text: "Barry Keoghan", secondaryText: "The Banshees of Inisherin" },
        {
          text: "Ke Huy Quan",
          secondaryText: "Everything Everywhere All at Once",
        },
      ],
      order: 3,
    },
    bestSupportingActress: {
      value: 4,
      name: "Actress in a Supporting Role",
      nominees: [
        {
          text: "Angela Bassett",
          secondaryText: "Black Panther: Wakanda Forever",
        },
        { text: "Hong Chau", secondaryText: "The Whale" },
        { text: "Kerry Condon", secondaryText: "The Banshees of Inisherin" },
        {
          text: "Jamie Lee Curtis",
          secondaryText: "Everything Everywhere All at Once",
        },
        {
          text: "Stephanie Hsu",
          secondaryText: "Everything Everywhere All at Once",
        },
      ],
      order: 4,
    },
    directing: {
      value: 8,
      name: "Directing",
      nominees: [
        { text: "The Banshees of Inisherin", secondaryText: "Martin McDonagh" },
        {
          text: "Everything Everywhere All at Once",
          secondaryText: "Daniel Kwan, Daniel Scheinert",
        },
        { text: "The Fabelmans", secondaryText: "Steven Spielberg" },
        { text: "Tár", secondaryText: "Todd Field" },
        { text: "Triangle of Sadness", secondaryText: "Ruben Östlund" },
      ],
      order: 5,
    },
    documentaryFeature: {
      value: 4,
      name: "Documentary Feature",
      nominees: [
        { text: "All That Breathes" },
        { text: "All the Beauty and the Bloodshed" },
        { text: "Fire of Love" },
        { text: "A House Made of Splinters" },
        { text: "Navalny" },
      ],
      order: 6,
    },
    internationalFilm: {
      value: 4,
      name: "International Feature Film",
      nominees: [
        { text: "All Quiet on the Western Front", secondaryText: "Germany" },
        { text: "Argentina, 1985", secondaryText: "Argentina" },
        { text: "Close", secondaryText: "Belgium" },
        { text: "EO", secondaryText: "Poland" },
        { text: "The Quiet Girl", secondaryText: "Ireland" },
      ],
      order: 7,
    },
    animatedFeature: {
      value: 4,
      name: "Animated Feature Film",
      nominees: [
        { text: "Guillermo del Toro’s Pinocchio" },
        { text: "Marcel the Shell With Shoes On" },
        { text: "Puss in Boots: The Last Wish" },
        { text: "The Sea Beast" },
        { text: "Turning Red" },
      ],
      order: 8,
    },
    writingAdaptedScreenplay: {
      value: 2,
      name: "Writing (Adapted Screenplay)",
      nominees: [
        { text: "All Quiet on the Western Front" },
        { text: "Glass Onion: A Knives Out Mystery" },
        { text: "Living" },
        { text: "Top Gun: Maverick" },
        { text: "Women Talking" },
      ],
      order: 9,
    },
    writingOriginalScreenplay: {
      value: 2,
      name: "Writing (Original Screenplay)",
      nominees: [
        { text: "The Banshees of Inisherin" },
        { text: "Everything Everywhere All at Once" },
        { text: "The Fabelmans" },
        { text: "Tár" },
        { text: "Triangle of Sadness" },
      ],
      order: 10,
    },
    cinematography: {
      value: 2,
      name: "Cinematography",
      nominees: [
        { text: "All Quiet on the Western Front" },
        { text: "Bardo, False Chronicle of a Handful of Truths" },
        { text: "Elvis" },
        { text: "Empire of Light" },
        { text: "Tár" },
      ],
      order: 11,
    },
    documentaryShort: {
      value: 2,
      name: "Documentary Short Subject",
      nominees: [
        { text: "The Elephant Whisperers" },
        { text: "Haulout" },
        { text: "How Do You Measure a Year?" },
        { text: "The Martha Mitchell Effect" },
        { text: "Stranger at the Gate" },
      ],
      order: 12,
    },
    filmEditing: {
      value: 1,
      name: "Film Editing",
      nominees: [
        { text: "The Banshees of Inisherin" },
        { text: "Elvis" },
        { text: "Everything Everywhere All at Once" },
        { text: "Tár" },
        { text: "Top Gun: Maverick" },
      ],
      order: 13,
    },
    musicOriginalScore: {
      value: 1,
      name: "Music (Original Score)",
      nominees: [
        {
          text: "All Quiet on the Western Front",
          secondaryText: "Volker Bertelmann",
        },
        { text: "Babylon", secondaryText: "Justin Hurwitz" },
        { text: "The Banshees of Inisherin", secondaryText: "Carter Burwell" },
        { text: "Everything Everywhere All at Once", secondaryText: "Son Lux" },
        { text: "The Fabelmans", secondaryText: "John Williams" },
      ],
      order: 14,
    },
    musicOriginalSong: {
      value: 1,
      name: "Music (Original Song)",
      nominees: [
        { text: "Tell It Like a Woman", secondaryText: "Applause" },
        { text: "Top Gun: Maverick", secondaryText: "Hold My Hand" },
        { text: "Black Panther: Wakanda Forever", secondaryText: "Lift Me Up" },
        { text: "RRR", secondaryText: "Naatu Naatu" },
        {
          text: "Everything Everywhere All at Once",
          secondaryText: "This Is a Life",
        },
      ],
      order: 15,
    },
    shortFilmAnimated: {
      value: 1,
      name: "Short Film (Animated)",
      nominees: [
        { text: "The Boy, the Mole, the Fox and the Horse" },
        { text: "The Flying Sailor" },
        { text: "Ice Merchants" },
        { text: "My Year of Dicks" },
        {
          text: "An Ostrich Told Me the World Is Fake and I Think I Believe It",
        },
      ],
      order: 16,
    },
    shortFilmLiveAction: {
      value: 1,
      name: "Short Film (Live Action)",
      nominees: [
        { text: "An Irish Goodbye" },
        { text: "Ivalu" },
        { text: "Le Pupille" },
        { text: "Night Ride" },
        { text: "The Red Suitcase" },
      ],
      order: 17,
    },
    sound: {
      value: 1,
      name: "Sound",
      nominees: [
        { text: "All Quiet on the Western Front" },
        { text: "Avatar: The Way of Water" },
        { text: "The Batman" },
        { text: "Elvis" },
        { text: "Top Gun: Maverick" },
      ],
      order: 18,
    },
    visualEffects: {
      value: 1,
      name: "Visual Effects",
      nominees: [
        { text: "All Quiet on the Western Front" },
        { text: "Avatar: The Way of Water" },
        { text: "The Batman" },
        { text: "Black Panther: Wakanda Forever" },
        { text: "Top Gun: Maverick" },
      ],
      order: 19,
    },
    productionDesign: {
      value: 1,
      name: "Production Design",
      nominees: [
        { text: "All Quiet on the Western Front" },
        { text: "Avatar: The Way of Water" },
        { text: "Babylon" },
        { text: "Elvis" },
        { text: "The Fabelmans" },
      ],
      order: 20,
    },
    costumeDesign: {
      value: 1,
      name: "Costume Design",
      nominees: [
        { text: "Babylon" },
        { text: "Black Panther: Wakanda Forever" },
        { text: "Elvis" },
        { text: "Everything Everywhere All at Once" },
        { text: "Mrs. Harris Goes to Paris" },
      ],
      order: 21,
    },
    makeupAndHairstyling: {
      value: 1,
      name: "Makeup and Hairstyling",
      nominees: [
        { text: "All Quiet on the Western Front" },
        { text: "The Batman" },
        { text: "Black Panther: Wakanda Forever" },
        { text: "Elvis" },
        { text: "The Whale" },
      ],
      order: 22,
    },
  },
};
