export default {
  categories: {
    bestPicture: {
      value: 16,
      name: "Best Picture",
      nominees: [
        { text: "Anora" },
        { text: "The Brutalist" },
        { text: "A Complete Unknown" },
        { text: "Conclave" },
        { text: "Dune: Part Two" },
        { text: "Emilia Pérez" },
        { text: "I'm Still Here" },
        { text: "Nickel Boys" },
        { text: "The Substance" },
        { text: "Wicked" },
      ],
      order: 0,
    },
    bestActor: {
      value: 8,
      name: "Actor in a Leading Role",
      nominees: [
        { text: "Adrien Brody", secondaryText: "The Brutalist" },
        { text: "Timothée Chalamet", secondaryText: "A Complete Unknown" },
        { text: "Colman Domingo", secondaryText: "Sing Sing" },
        { text: "Ralph Fiennes", secondaryText: "Conclave" },
        { text: "Sebastian Stan", secondaryText: "The Apprentice" },
      ],
      order: 1,
    },
    bestActress: {
      value: 8,
      name: "Actress in a Leading Role",
      nominees: [
        { text: "Cynthia Erivo", secondaryText: "Wicked" },
        { text: "Karla Sofía Gascón", secondaryText: "Emilia Pérez" },
        { text: "Mikey Madison", secondaryText: "Anora" },
        { text: "Demi Moore", secondaryText: "The Substance" },
        { text: "Fernanda Torres", secondaryText: "I'm Still Here" },
      ],
      order: 2,
    },
    bestSupportingActor: {
      value: 4,
      name: "Actor in a Supporting Role",
      nominees: [
        { text: "Yura Borisov", secondaryText: "Anora" },
        { text: "Kieran Culkin", secondaryText: "A Real Pain" },
        { text: "Edward Norton", secondaryText: "A Complete Unknown" },
        { text: "Guy Pearce", secondaryText: "The Brutalist" },
        { text: "Jeremy Strong", secondaryText: "The Apprentice" },
      ],
      order: 3,
    },
    bestSupportingActress: {
      value: 4,
      name: "Actress in a Supporting Role",
      nominees: [
        { text: "Monica Barbaro", secondaryText: "A Complete Unknown" },
        { text: "Ariana Grande", secondaryText: "Wicked" },
        { text: "Felicity Jones", secondaryText: "The Brutalist" },
        { text: "Isabella Rossellini", secondaryText: "Conclave" },
        { text: "Zoe Saldaña", secondaryText: "Emilia Pérez" },
      ],
      order: 4,
    },
    directing: {
      value: 8,
      name: "Directing",
      nominees: [
        { text: "Anora", secondaryText: "Sean Baker" },
        { text: "The Brutalist", secondaryText: "Brady Corbet" },
        { text: "A Complete Unknown", secondaryText: "James Mangold" },
        { text: "Emilia Pérez", secondaryText: "Jacques Audiard" },
        { text: "The Substance", secondaryText: "Coralie Fargeat" },
      ],
      order: 5,
    },
    documentaryFeature: {
      value: 4,
      name: "Documentary Feature",
      nominees: [
        { text: "Black Box Diaries" },
        { text: "No Other Land" },
        { text: "Porcelain War" },
        { text: "Soundtrack to a Coup d'Etat" },
        { text: "Sugarcane" },
      ],
      order: 6,
    },
    internationalFilm: {
      value: 4,
      name: "International Feature Film",
      nominees: [
        { text: "I'm Still Here", secondaryText: "Brazil" },
        { text: "The Girl with the Needle", secondaryText: "Denmark" },
        { text: "Emilia Pérez", secondaryText: "France" },
        { text: "The Seed of the Sacred Fig", secondaryText: "Germany" },
        { text: "Flow", secondaryText: "Latvia" },
      ],
      order: 7,
    },
    animatedFeature: {
      value: 4,
      name: "Animated Feature Film",
      nominees: [
        { text: "Flow" },
        { text: "Inside Out 2" },
        { text: "Memoir of a Snail" },
        { text: "Wallace & Gromit: Vengeance Most Fowl" },
        { text: "The Wild Robot" },
      ],
      order: 8,
    },
    writingAdaptedScreenplay: {
      value: 2,
      name: "Writing (Adapted Screenplay)",
      nominees: [
        { text: "A Complete Unknown" },
        { text: "Conclave" },
        { text: "Emilia Pérez" },
        { text: "Nickel Boys" },
        { text: "Sing Sing" },
      ],
      order: 9,
    },
    writingOriginalScreenplay: {
      value: 2,
      name: "Writing (Original Screenplay)",
      nominees: [
        { text: "Anora" },
        { text: "The Brutalist" },
        { text: "A Real Pain" },
        { text: "September 5" },
        { text: "The Substance" },
      ],
      order: 10,
    },
    cinematography: {
      value: 2,
      name: "Cinematography",
      nominees: [
        { text: "The Brutalist" },
        { text: "Dune: Part Two" },
        { text: "Emilia Pérez" },
        { text: "Maria" },
        { text: "Nosferatu" },
      ],
      order: 11,
    },
    documentaryShort: {
      value: 2,
      name: "Documentary Short Subject",
      nominees: [
        { text: "Death by Numbers" },
        { text: "I Am Ready, Warden" },
        { text: "Incident" },
        { text: "Instruments of a Beating Heart" },
        { text: "The Only Girl in the Orchestra" },
      ],
      order: 12,
    },
    filmEditing: {
      value: 1,
      name: "Film Editing",
      nominees: [
        { text: "Anora" },
        { text: "The Brutalist" },
        { text: "Conclave" },
        { text: "Emilia Pérez" },
        { text: "Wicked" },
      ],
      order: 13,
    },
    musicOriginalScore: {
      value: 1,
      name: "Music (Original Score)",

      nominees: [
        { text: "The Brutalist", secondaryText: "Daniel Blumberg" },
        { text: "Conclave", secondaryText: "Volker Bertelmann" },
        { text: "Emilia Pérez", secondaryText: "Clément Ducol & Camille" },
        { text: "Wicked", secondaryText: "John Powell & Stephen Schwartz" },
        { text: "The Wild Robot", secondaryText: "Kris Bowers" },
      ],
      order: 14,
    },
    musicOriginalSong: {
      value: 1,
      name: "Music (Original Song)",
      nominees: [
        {
          text: "El Mal",
          secondaryText: "Emilia Pérez",
        },
        {
          text: "The Journey",
          secondaryText: "The Six Triple Eight",
        },
        {
          text: "Like A Bird",
          secondaryText: "Sing Sing",
        },
        {
          text: "Mi Camino",
          secondaryText: "Emilia Pérez",
        },
        {
          text: "Never Too Late",
          secondaryText: "Elton John: Never Too Late",
        },
      ],
      order: 15,
    },
    shortFilmAnimated: {
      value: 1,
      name: "Short Film (Animated)",
      nominees: [
        { text: "Beautiful Men" },
        { text: "In the Shadow of the Cypress" },
        { text: "Magic Candies" },
        { text: "Wander to Wonder" },
        { text: "Yuck!" },
      ],
      order: 16,
    },
    shortFilmLiveAction: {
      value: 1,
      name: "Short Film (Live Action)",
      nominees: [
        { text: "A Lien" },
        { text: "Anuja" },
        { text: "I'm Not a Robot" },
        { text: "The Last Ranger" },
        { text: "The Man Who Could Not Remain Silent" },
      ],
      order: 17,
    },
    sound: {
      value: 1,
      name: "Sound",
      nominees: [
        { text: "A Complete Unknown" },
        { text: "Dune: Part Two" },
        { text: "Emilia Pérez" },
        { text: "Wicked" },
        { text: "The Wild Robot" },
      ],
      order: 18,
    },
    visualEffects: {
      value: 1,
      name: "Visual Effects",
      nominees: [
        { text: "Alien: Romulus" },
        { text: "Better Man" },
        { text: "Dune: Part Two" },
        { text: "Kingdom of the Planet of the Apes" },
        { text: "Wicked" },
      ],
      order: 19,
    },
    productionDesign: {
      value: 1,
      name: "Production Design",
      nominees: [
        { text: "The Brutalist" },
        { text: "Conclave" },
        { text: "Dune: Part Two" },
        { text: "Nosferatu" },
        { text: "Wicked" },
      ],
      order: 20,
    },
    costumeDesign: {
      value: 1,
      name: "Costume Design",
      nominees: [
        { text: "A Complete Unknown" },
        { text: "Conclave" },
        { text: "Gladiator II" },
        { text: "Nosferatu" },
        { text: "Wicked" },
      ],
      order: 21,
    },
    makeupAndHairstyling: {
      value: 1,
      name: "Makeup and Hairstyling",
      nominees: [
        { text: "A Different Man" },
        { text: "Emilia Pérez" },
        { text: "Nosferatu" },
        { text: "The Substance" },
        { text: "Wicked" },
      ],
      order: 22,
    },
  },
};
