export default {
  categories: {
    bestPicture: {
      value: 16,
      name: "Best Picture",
      nominees: [
        { text: "Bugonia" },
        { text: "F1" },
        { text: "Frankenstein" },
        { text: "Hamnet" },
        { text: "Marty Supreme" },
        { text: "One Battle After Another" },
        { text: "The Secret Agent" },
        { text: "Sentimental Value" },
        { text: "Sinners" },
        { text: "Train Dreams" },
      ],
      order: 0,
    },
    bestActor: {
      value: 8,
      name: "Actor in a Leading Role",
      nominees: [
        { text: "Timothée Chalamet", secondaryText: "Marty Supreme" },
        {
          text: "Leonardo DiCaprio",
          secondaryText: "One Battle After Another",
        },
        { text: "Ethan Hawke", secondaryText: "Blue Moon" },
        { text: "Michael B. Jordan", secondaryText: "Sinners" },
        { text: "Wagner Moura", secondaryText: "The Secret Agent" },
      ],
      order: 1,
    },
    bestActress: {
      value: 8,
      name: "Actress in a Leading Role",
      nominees: [
        { text: "Jessie Buckley", secondaryText: "Hamnet" },
        { text: "Rose Byrne", secondaryText: "If I Had Legs I'd Kick You" },
        { text: "Kate Hudson", secondaryText: "Song Sung Blue" },
        { text: "Renate Reinsve", secondaryText: "Sentimental Value" },
        { text: "Emma Stone", secondaryText: "Bugonia" },
      ],
      order: 2,
    },
    bestSupportingActor: {
      value: 4,
      name: "Actor in a Supporting Role",
      nominees: [
        {
          text: "Benicio del Toro",
          secondaryText: "One Battle After Another",
        },
        { text: "Jacob Elordi", secondaryText: "Frankenstein" },
        { text: "Delroy Lindo", secondaryText: "Sinners" },
        { text: "Sean Penn", secondaryText: "One Battle After Another" },
        { text: "Stellan Skarsgård", secondaryText: "Sentimental Value" },
      ],
      order: 3,
    },
    bestSupportingActress: {
      value: 4,
      name: "Actress in a Supporting Role",
      nominees: [
        { text: "Elle Fanning", secondaryText: "Sentimental Value" },
        {
          text: "Inga Ibsdotter Lilleaas",
          secondaryText: "Sentimental Value",
        },
        { text: "Amy Madigan", secondaryText: "Weapons" },
        { text: "Wunmi Mosaku", secondaryText: "Sinners" },
        { text: "Teyana Taylor", secondaryText: "One Battle After Another" },
      ],
      order: 4,
    },
    directing: {
      value: 8,
      name: "Directing",
      nominees: [
        { text: "Hamnet", secondaryText: "Chloé Zhao" },
        { text: "Marty Supreme", secondaryText: "Josh Safdie" },
        {
          text: "One Battle After Another",
          secondaryText: "Paul Thomas Anderson",
        },
        { text: "Sentimental Value", secondaryText: "Joachim Trier" },
        { text: "Sinners", secondaryText: "Ryan Coogler" },
      ],
      order: 5,
    },
    documentaryFeature: {
      value: 4,
      name: "Documentary Feature",
      nominees: [
        { text: "The Alabama Solution" },
        { text: "Come See Me in the Good Light" },
        { text: "Cutting Through Rocks" },
        { text: "Mr. Nobody Against Putin" },
        { text: "The Perfect Neighbor" },
      ],
      order: 6,
    },
    internationalFilm: {
      value: 4,
      name: "International Feature Film",
      nominees: [
        { text: "The Secret Agent", secondaryText: "Brazil" },
        { text: "It Was Just an Accident", secondaryText: "France" },
        { text: "Sentimental Value", secondaryText: "Norway" },
        { text: "Sirât", secondaryText: "Spain", movieDBName: "Sirât" },
        { text: "The Voice of Hind Rajab", secondaryText: "Tunisia" },
      ],
      order: 7,
    },
    animatedFeature: {
      value: 4,
      name: "Animated Feature Film",
      nominees: [
        { text: "Arco" },
        { text: "Elio" },
        { text: "K-Pop: Demon Hunters", movieDBName: "KPop Demon Hunters" },
        { text: "Little Amélie or The Character of Rain" },
        { text: "Zootopia 2" },
      ],
      order: 8,
    },
    writingAdaptedScreenplay: {
      value: 2,
      name: "Writing (Adapted Screenplay)",
      nominees: [
        { text: "Bugonia" },
        { text: "Frankenstein" },
        { text: "Hamnet" },
        { text: "One Battle After Another" },
        { text: "Train Dreams" },
      ],
      order: 9,
    },
    writingOriginalScreenplay: {
      value: 2,
      name: "Writing (Original Screenplay)",
      nominees: [
        { text: "Blue Moon" },
        { text: "It Was Just an Accident" },
        { text: "Marty Supreme" },
        { text: "Sentimental Value" },
        { text: "Sinners" },
      ],
      order: 10,
    },
    cinematography: {
      value: 2,
      name: "Cinematography",
      nominees: [
        { text: "Frankenstein" },
        { text: "Marty Supreme" },
        { text: "One Battle After Another" },
        { text: "Sinners" },
        { text: "Train Dreams" },
      ],
      order: 11,
    },
    documentaryShort: {
      value: 2,
      name: "Documentary Short Subject",
      nominees: [
        { text: "All the Empty Rooms" },
        {
          text: "Armed Only with a Camera: The Life and Death of Brent Renaud",
        },
        { text: "Children No More: Were and Are Gone" },
        { text: "The Devil Is Busy" },
        { text: "Perfectly a Strangeness" },
      ],
      order: 12,
    },
    filmEditing: {
      value: 1,
      name: "Film Editing",
      nominees: [
        { text: "F1" },
        { text: "Marty Supreme" },
        { text: "One Battle After Another" },
        { text: "Sentimental Value" },
        { text: "Sinners" },
      ],
      order: 13,
    },
    musicOriginalScore: {
      value: 1,
      name: "Music (Original Score)",
      nominees: [
        { text: "Bugonia", secondaryText: "Jerskin Fendrix" },
        { text: "Frankenstein", secondaryText: "Alexandre Desplat" },
        { text: "Hamnet", secondaryText: "Max Richter" },
        {
          text: "One Battle After Another",
          secondaryText: "Jonny Greenwood",
        },
        { text: "Sinners", secondaryText: "Ludwig Göransson" },
      ],
      order: 14,
    },
    musicOriginalSong: {
      value: 1,
      name: "Music (Original Song)",
      nominees: [
        {
          text: "Dear Me",
          secondaryText: "Diane Warren: Relentless",
        },
        {
          text: "Golden",
          secondaryText: "K-Pop: Demon Hunters",
          movieDBName: "KPop Demon Hunters",
        },
        {
          text: "I Lied To You",
          secondaryText: "Sinners",
        },
        {
          text: "Sweet Dreams of Joy",
          secondaryText: "Viva Verdi!",
        },
        {
          text: "Train Dreams",
          secondaryText: "Train Dreams",
        },
      ],
      order: 15,
    },
    shortFilmAnimated: {
      value: 1,
      name: "Short Film (Animated)",
      nominees: [
        { text: "Butterfly" },
        { text: "Forevergreen" },
        { text: "The Girl Who Cried Pearls" },
        { text: "Retirement Plan" },
        { text: "The Three Sisters" },
      ],
      order: 16,
    },
    shortFilmLiveAction: {
      value: 1,
      name: "Short Film (Live Action)",
      nominees: [
        { text: "Butcher's Stain" },
        { text: "A Friend of Dorothy" },
        { text: "Jane Austen's Period Drama" },
        { text: "The Singers" },
        { text: "Two People Exchanging Saliva" },
      ],
      order: 17,
    },
    sound: {
      value: 1,
      name: "Sound",
      nominees: [
        { text: "F1" },
        { text: "Frankenstein" },
        { text: "One Battle After Another" },
        { text: "Sinners" },
        { text: "Sirât", movieDBName: "Sirât" },
      ],
      order: 18,
    },
    visualEffects: {
      value: 1,
      name: "Visual Effects",
      nominees: [
        { text: "Avatar: Fire and Ash" },
        { text: "F1" },
        { text: "Jurassic World Rebirth" },
        { text: "The Lost Bus" },
        { text: "Sinners" },
      ],
      order: 19,
    },
    productionDesign: {
      value: 1,
      name: "Production Design",
      nominees: [
        { text: "Frankenstein" },
        { text: "Hamnet" },
        { text: "Marty Supreme" },
        { text: "One Battle After Another" },
        { text: "Sinners" },
      ],
      order: 20,
    },
    costumeDesign: {
      value: 1,
      name: "Costume Design",
      nominees: [
        { text: "Avatar: Fire and Ash" },
        { text: "Frankenstein" },
        { text: "Hamnet" },
        { text: "Marty Supreme" },
        { text: "Sinners" },
      ],
      order: 21,
    },
    makeupAndHairstyling: {
      value: 1,
      name: "Makeup and Hairstyling",
      nominees: [
        { text: "Frankenstein" },
        { text: "Kokuho" },
        { text: "Sinners" },
        { text: "The Smashing Machine" },
        { text: "The Ugly Stepsister" },
      ],
      order: 22,
    },
    casting: {
      value: 1,
      name: "Casting",
      nominees: [
        { text: "Hamnet", secondaryText: "Nina Gold" },
        { text: "Marty Supreme", secondaryText: "Jennifer Venditti" },
        {
          text: "One Battle After Another",
          secondaryText: "Cassandra Kulukundis",
        },
        { text: "The Secret Agent", secondaryText: "Gabriel Domingues" },
        { text: "Sinners", secondaryText: "Francine Maisler" },
      ],
      order: 23,
    },
  },
};
